// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(BancoAPIContext))]
    [Migration("20240828000623_Teste")]
    partial class Teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Aviso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<int>("Nivel")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SubPrefeitura_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("SubPrefeitura_Id");

                    b.ToTable("TBL_Aviso");
                });

            modelBuilder.Entity("DAL.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.ToTable("TBL_Cidade");
                });

            modelBuilder.Entity("DAL.Models.Nuvem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<float>("Dia_1")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_2")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_3")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_4")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_5")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_6")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_7")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("Id");

                    b.ToTable("TBL_Nuvem");
                });

            modelBuilder.Entity("DAL.Models.Precipitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<float>("Dia_1")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_2")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_3")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_4")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_5")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_6")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_7")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("Id");

                    b.ToTable("TBL_Precipitacao");
                });

            modelBuilder.Entity("DAL.Models.Previsao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nuvem_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Precipitacao_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Regiao_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Temperatura_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Umidade_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Ventania_Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Nuvem_Id");

                    b.HasIndex("Precipitacao_Id");

                    b.HasIndex("Regiao_Id");

                    b.HasIndex("Temperatura_Id");

                    b.HasIndex("Umidade_Id");

                    b.HasIndex("Ventania_Id");

                    b.ToTable("TBL_Previsao");
                });

            modelBuilder.Entity("DAL.Models.Regiao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cidade_Id")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("Cidade_Id");

                    b.ToTable("TBL_Regiao");
                });

            modelBuilder.Entity("DAL.Models.SubPrefeitura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("Regiao_Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Regiao_Id");

                    b.ToTable("TBL_SubPrefeitura");
                });

            modelBuilder.Entity("DAL.Models.Temperatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<float>("Dia_1")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_2")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_3")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_4")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_5")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_6")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_7")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("Id");

                    b.ToTable("TBL_Temperatura");
                });

            modelBuilder.Entity("DAL.Models.Umidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<float>("Dia_1")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_2")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_3")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_4")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_5")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_6")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_7")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("Id");

                    b.ToTable("TBL_Umidade");
                });

            modelBuilder.Entity("DAL.Models.Ventania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<float>("Dia_1")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_2")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_3")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_4")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_5")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_6")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<float>("Dia_7")
                        .HasColumnType("BINARY_FLOAT");

                    b.HasKey("Id");

                    b.ToTable("TBL_Ventania");
                });

            modelBuilder.Entity("DAL.Models.Aviso", b =>
                {
                    b.HasOne("DAL.Models.SubPrefeitura", "SubPrefeitura")
                        .WithMany()
                        .HasForeignKey("SubPrefeitura_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubPrefeitura");
                });

            modelBuilder.Entity("DAL.Models.Previsao", b =>
                {
                    b.HasOne("DAL.Models.Nuvem", "Nuvem")
                        .WithMany("Previsoes")
                        .HasForeignKey("Nuvem_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Precipitacao", "Precipitacao")
                        .WithMany("Previsoes")
                        .HasForeignKey("Precipitacao_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Regiao", "Regiao")
                        .WithMany()
                        .HasForeignKey("Regiao_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Temperatura", "Temperatura")
                        .WithMany("Previsoes")
                        .HasForeignKey("Temperatura_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Umidade", "Umidade")
                        .WithMany("Previsoes")
                        .HasForeignKey("Umidade_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Ventania", "Ventania")
                        .WithMany("Previsoes")
                        .HasForeignKey("Ventania_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nuvem");

                    b.Navigation("Precipitacao");

                    b.Navigation("Regiao");

                    b.Navigation("Temperatura");

                    b.Navigation("Umidade");

                    b.Navigation("Ventania");
                });

            modelBuilder.Entity("DAL.Models.Regiao", b =>
                {
                    b.HasOne("DAL.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("Cidade_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("DAL.Models.SubPrefeitura", b =>
                {
                    b.HasOne("DAL.Models.Regiao", "Regiao")
                        .WithMany()
                        .HasForeignKey("Regiao_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("DAL.Models.Nuvem", b =>
                {
                    b.Navigation("Previsoes");
                });

            modelBuilder.Entity("DAL.Models.Precipitacao", b =>
                {
                    b.Navigation("Previsoes");
                });

            modelBuilder.Entity("DAL.Models.Temperatura", b =>
                {
                    b.Navigation("Previsoes");
                });

            modelBuilder.Entity("DAL.Models.Umidade", b =>
                {
                    b.Navigation("Previsoes");
                });

            modelBuilder.Entity("DAL.Models.Ventania", b =>
                {
                    b.Navigation("Previsoes");
                });
#pragma warning restore 612, 618
        }
    }
}
