/*DROP TABLE TBL_Previsao CASCADE CONSTRAINTS;
DROP TABLE TBL_Previsao_Futura CASCADE CONSTRAINTS;
DROP TABLE TBL_Distrito CASCADE CONSTRAINTS;
DROP TABLE TBL_Zona CASCADE CONSTRAINTS;
DROP TABLE TBL_Municipio CASCADE CONSTRAINTS;*/


-- TBL_Municipio
CREATE TABLE TBL_Municipio (
    CD_MUN        NUMBER(7, 0) PRIMARY KEY, -- CD_MUN é a chave primária com até 7 dígitos
    NM_MUN        VARCHAR2(100) NOT NULL,
    SG_Estado     CHAR(2) NOT NULL,
    AREA_KM2      NUMBER(10, 2) NOT NULL,
    geometry      SDO_GEOMETRY, -- Tipo para armazenar o polígono de coordenadas
    CORD_CENTRAL  SDO_GEOMETRY  -- Tipo para armazenar o ponto central do município
);

COMMENT ON COLUMN TBL_Municipio.CD_MUN IS
    'Esta coluna irá receber o código do município e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Municipio.NM_MUN IS
    'Esta coluna irá receber o nome do município e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Municipio.SG_Estado IS
    'Esta coluna irá receber a sigla do estado do município e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Municipio.AREA_KM2 IS
    'Esta coluna irá receber a área do município em quilômetros quadrados.';

COMMENT ON COLUMN TBL_Municipio.geometry IS
    'Esta coluna irá receber o polígono de coordenadas do município.';

COMMENT ON COLUMN TBL_Municipio.CORD_CENTRAL IS
    'Esta coluna irá receber a coordenada central do município.';



-- TBL_Zona
CREATE TABLE TBL_Zona (
    Id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome_Zona  VARCHAR2(50) NOT NULL,
    geometry   SDO_GEOMETRY, -- Tipo para armazenar o polígono de coordenadas
    CORD_CENTRAL SDO_GEOMETRY,  -- Tipo para armazenar o ponto central da zona
    Municipio_Id  NUMBER(7, 0) NOT NULL, -- Referencia CD_MUN na tabela TBL_Municipio
    FOREIGN KEY (Municipio_Id) REFERENCES TBL_Municipio(CD_MUN)
);

COMMENT ON COLUMN TBL_Zona.Id IS
    'Esta coluna irá receber o Id da zona e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Zona.Nome_Zona IS
    'Esta coluna irá receber o nome da zona e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Zona.Municipio_Id IS
    'Esta coluna irá receber o id da cidade e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Zona.geometry IS
    'Esta coluna irá receber o polígono de coordenadas da zona.';

COMMENT ON COLUMN TBL_Zona.CORD_CENTRAL IS
    'Esta coluna irá receber a coordenada central da zona.';



-- TBL_Distrito
CREATE TABLE TBL_Distrito (
    CD_DIST      NUMBER(9, 0) PRIMARY KEY, -- CD_DIST é a chave primária com até 7 dígitos
    NM_DIST      VARCHAR2(100) NOT NULL,
    geometry   SDO_GEOMETRY, -- Tipo para armazenar o polígono de coordenadas
    CORD_CENTRAL SDO_GEOMETRY, -- Tipo para armazenar o ponto central do distrito
    Zona_Id         NUMBER NOT NULL,
    FOREIGN KEY (Zona_Id) REFERENCES TBL_Zona(Id)
);

COMMENT ON COLUMN TBL_Distrito.CD_DIST IS
    'Esta coluna irá receber o código do distrito e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Distrito.NM_DIST IS
    'Esta coluna irá receber o nome do distrito e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Distrito.geometry IS
    'Esta coluna irá receber o polígono de coordenadas do distrito.';

COMMENT ON COLUMN TBL_Distrito.CORD_CENTRAL IS
    'Esta coluna irá receber a coordenada central do distrito.';

COMMENT ON COLUMN TBL_Distrito.Zona_Id IS
    'Esta coluna irá receber o Nome da Zona associado ao distrito.';



-- Tabela TBL_Previsao (contém todos os dados climáticos diretamente)
CREATE TABLE TBL_Previsao (
    Id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Zona_Id         NUMBER NOT NULL,
    Data            DATE NOT NULL,
    Hora            NUMBER(2) NOT NULL,
    Temperatura_Max NUMBER(5, 2),
    Temperatura_Min NUMBER(5, 2),
    Umidade_Max     NUMBER(5, 2),
    Umidade_Min     NUMBER(5, 2),
    Velocidade_Vento NUMBER(5, 2),
    Volume_Precipitacao NUMBER(5, 2),
    Tipo_Nuvem      VARCHAR2(50),
    Pressao_Atm     NUMBER(5, 2),
    FOREIGN KEY (Zona_Id) REFERENCES TBL_Zona(Id)
);

COMMENT ON COLUMN TBL_Previsao.Id IS
    'Esta coluna irá receber o Id da previsão registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao.Zona_Id IS
    'Esta coluna irá receber o Id da zona correspondente e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao.Data IS
    'Esta coluna irá receber a data da previsão registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao.Hora IS
    'Esta coluna irá receber a hora da previsão registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao.Temperatura_Max IS
    'Esta coluna irá receber a temperatura máxima registrada na previsão.';

COMMENT ON COLUMN TBL_Previsao.Temperatura_Min IS
    'Esta coluna irá receber a temperatura mínima registrada na previsão.';

COMMENT ON COLUMN TBL_Previsao.Umidade_Max IS
    'Esta coluna irá receber a umidade máxima registrada na previsão.';

COMMENT ON COLUMN TBL_Previsao.Umidade_Min IS
    'Esta coluna irá receber a umidade mínima registrada na previsão.';

COMMENT ON COLUMN TBL_Previsao.Velocidade_Vento IS
    'Esta coluna irá receber a velocidade do vento registrada na previsão.';

COMMENT ON COLUMN TBL_Previsao.Volume_Precipitacao IS
    'Esta coluna irá receber o volume de precipitação registrado na previsão.';

COMMENT ON COLUMN TBL_Previsao.Tipo_Nuvem IS
    'Esta coluna irá receber o tipo de nuvem registrado na previsão.';

COMMENT ON COLUMN TBL_Previsao.Pressao_Atm IS
    'Esta coluna irá receber o valor da pressão atmosférica registrada na previsão.';


-- TBL_Previsao_Futura (ajustes sugeridos)
CREATE TABLE TBL_Previsao_Futura (
    Id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Zona_Id         NUMBER NOT NULL,
    Data_Referencia DATE NOT NULL,
    Data_Futura     TIMESTAMP NOT NULL,
    Temperatura_Max NUMBER(5, 2),
    Temperatura_Min NUMBER(5, 2),
    Umidade_Max     NUMBER(5, 2),
    Umidade_Min     NUMBER(5, 2),
    Ventania        NUMBER(5, 2),
    Precipitacao    NUMBER(5, 2),
    Nuvem           VARCHAR2(50),
    Pressao         NUMBER(6, 2),
    FOREIGN KEY (Zona_Id) REFERENCES TBL_Zona(Id)
);

COMMENT ON COLUMN TBL_Previsao_Futura.Id IS
    'Esta coluna irá receber o Id da previsão futura registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao_Futura.Zona_Id IS
    'Esta coluna irá receber a chave estrangeira o Id da zona registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao_Futura.Data_Referencia IS
    'Esta coluna irá receber a data de referência da previsão futura e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao_Futura.Data_Futura IS
    'Esta coluna irá receber a data futura prevista e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao_Futura.Temperatura_Max IS
    'Esta coluna irá receber a temperatura máxima futura.';
    
COMMENT ON COLUMN TBL_Previsao_Futura.Temperatura_Min IS
    'Esta coluna irá receber a temperatura minima futura.';
	
COMMENT ON COLUMN TBL_Previsao_Futura.Umidade_Max IS
    'Esta coluna irá receber a umidade futura.';
    
COMMENT ON COLUMN TBL_Previsao_Futura.Umidade_Min IS
    'Esta coluna irá receber a umidade futura.';

COMMENT ON COLUMN TBL_Previsao_Futura.Ventania IS
    'Esta coluna irá receber a ventania futura.';

COMMENT ON COLUMN TBL_Previsao_Futura.Precipitacao IS
    'Esta coluna irá receber a precipitação futura.';

COMMENT ON COLUMN TBL_Previsao_Futura.Nuvem IS
    'Esta coluna irá receber a nuvem futura.';

COMMENT ON COLUMN TBL_Previsao_Futura.Pressao IS
    'Esta coluna irá receber a para a pressão atmosférica futura.';