/*DROP TABLE TBL_Previsao CASCADE CONSTRAINTS;
DROP TABLE TBL_Previsao_Futura CASCADE CONSTRAINTS;
DROP TABLE TBL_Temperatura CASCADE CONSTRAINTS;
DROP TABLE TBL_Umidade CASCADE CONSTRAINTS;
DROP TABLE TBL_Ventania CASCADE CONSTRAINTS;
DROP TABLE TBL_Precipitacao CASCADE CONSTRAINTS;
DROP TABLE TBL_Nuvem CASCADE CONSTRAINTS;
DROP TABLE TBL_Pressao CASCADE CONSTRAINTS;
DROP TABLE TBL_Distrito CASCADE CONSTRAINTS;
DROP TABLE TBL_Zona CASCADE CONSTRAINTS;
DROP TABLE TBL_Municipio CASCADE CONSTRAINTS;*/


CREATE TABLE TBL_Municipio (
    CD_MUN        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NM_MUN        VARCHAR2(100) NOT NULL,
    SG_Estado     CHAR(2) NOT NULL,
    AREA_KM2      FLOAT(10) NOT NULL,
    geometry      SDO_GEOMETRY, -- Tipo para armazenar o polígono de coordenadas
    CORD_CENTRAL  SDO_GEOMETRY  -- Tipo para armazenar o ponto central do município
);

COMMENT ON COLUMN TBL_Municipio.CD_MUN IS
    'Esta coluna irá receber o código do município e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Municipio.NM_MUN IS
    'Esta coluna irá receber o nome do município e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Municipio.SG_Estado IS
    'Esta coluna irá receber a sigla do estado do município e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Municipio.AREA_KM2 IS
    'Esta coluna irá receber a área do município em quilômetros quadrados.';

COMMENT ON COLUMN TBL_Municipio.geometry IS
    'Esta coluna irá receber o polígono de coordenadas do município.';

COMMENT ON COLUMN TBL_Municipio.CORD_CENTRAL IS
    'Esta coluna irá receber a coordenada central do município.';



CREATE TABLE TBL_Zona (
    Id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome       VARCHAR2(50) NOT NULL,
	geometry      SDO_GEOMETRY, -- Tipo para armazenar o polígono de coordenadas
    CORD_CENTRAL  SDO_GEOMETRY,  -- Tipo para armazenar o ponto central da zona
    Municipio_Id  NUMBER NOT NULL,
    FOREIGN KEY (Municipio_Id) REFERENCES TBL_Municipio(CD_MUN)
);

COMMENT ON COLUMN TBL_Zona.Id IS
    'Esta coluna irá receber o Id da zona e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Zona.Nome IS
    'Esta coluna irá receber o nome da zona e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Zona.Municipio_Id IS
    'Esta coluna irá receber o id da cidade e seu conteúdo é obrigatório.';
	
COMMENT ON COLUMN TBL_Zona.geometry IS
    'Esta coluna irá receber o polígono de coordenadas da zona.';

COMMENT ON COLUMN TBL_Zona.CORD_CENTRAL IS
    'Esta coluna irá receber a coordenada central da zona.';



CREATE TABLE TBL_Distrito (
    CD_DIST       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NM_DIST       VARCHAR2(100) NOT NULL,
    geometry      SDO_GEOMETRY, -- Tipo para armazenar o polígono de coordenadas
    CORD_CENTRAL  SDO_GEOMETRY, -- Tipo para armazenar o ponto central do distrito
    Zona_id       NUMBER NOT NULL,
    FOREIGN KEY (Zona_id) REFERENCES TBL_Zona(Id)
);

COMMENT ON COLUMN TBL_Distrito.CD_DIST IS
    'Esta coluna irá receber o código do distrito e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Distrito.NM_DIST IS
    'Esta coluna irá receber o nome do distrito e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Distrito.geometry IS
    'Esta coluna irá receber o polígono de coordenadas do distrito.';

COMMENT ON COLUMN TBL_Distrito.CORD_CENTRAL IS
    'Esta coluna irá receber a coordenada central do distrito.';

COMMENT ON COLUMN TBL_Distrito.Zona_id IS
    'Esta coluna irá receber o Id da Zona associado ao distrito.';



CREATE TABLE TBL_Temperatura (
    Id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data            DATE NOT NULL,
    Hora            NUMBER(2) NOT NULL,
    Temperatura_Max FLOAT(3),
    Temperatura_Min FLOAT(3)
);

COMMENT ON COLUMN TBL_Temperatura.Id IS
    'Esta coluna irá receber o Id da temperatura registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Temperatura.Data IS
    'Esta coluna irá receber a data da temperatura registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Temperatura.Hora IS
    'Esta coluna irá receber a hora da temperatura registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Temperatura.Temperatura_Max IS
    'Esta coluna irá receber a temperatura máxima registrada.';

COMMENT ON COLUMN TBL_Temperatura.Temperatura_Min IS
    'Esta coluna irá receber a temperatura mínima registrada.';


CREATE TABLE TBL_Umidade (
    Id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data          DATE NOT NULL,
    Hora          NUMBER(2) NOT NULL,
    Umidade_Max   FLOAT(3),
    Umidade_Min   FLOAT(3)
);

COMMENT ON COLUMN TBL_Umidade.Id IS
    'Esta coluna irá receber o Id da umidade registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Umidade.Data IS
    'Esta coluna irá receber a data da umidade registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Umidade.Hora IS
    'Esta coluna irá receber a hora da umidade registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Umidade.Umidade_Max IS
    'Esta coluna irá receber a umidade máxima registrada.';

COMMENT ON COLUMN TBL_Umidade.Umidade_Min IS
    'Esta coluna irá receber a umidade mínima registrada.';


CREATE TABLE TBL_Ventania (
    Id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data          DATE NOT NULL,
    Hora          NUMBER(2) NOT NULL,
    Velocidade    FLOAT(3)
);

COMMENT ON COLUMN TBL_Ventania.Id IS
    'Esta coluna irá receber o Id da ventania registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Ventania.Data IS
    'Esta coluna irá receber a data da ventania registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Ventania.Hora IS
    'Esta coluna irá receber a hora da ventania registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Ventania.Velocidade IS
    'Esta coluna irá receber a velocidade da ventania registrada.';


CREATE TABLE TBL_Precipitacao (
    Id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data          DATE NOT NULL,
    Hora          NUMBER(2) NOT NULL,
    Volume        FLOAT(3)
);

COMMENT ON COLUMN TBL_Precipitacao.Id IS
    'Esta coluna irá receber o Id da precipitação registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Precipitacao.Data IS
    'Esta coluna irá receber a data da precipitação registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Precipitacao.Hora IS
    'Esta coluna irá receber a hora da precipitação registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Precipitacao.Volume IS
    'Esta coluna irá receber o volume de precipitação registrada.';


CREATE TABLE TBL_Nuvem (
    Id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data          DATE NOT NULL,
    Hora          NUMBER(2) NOT NULL,
    Tipo          VARCHAR2(50)
);

COMMENT ON COLUMN TBL_Nuvem.Id IS
    'Esta coluna irá receber o Id da nuvem registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Nuvem.Data IS
    'Esta coluna irá receber a data da nuvem registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Nuvem.Hora IS
    'Esta coluna irá receber a hora da nuvem registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Nuvem.Tipo IS
    'Esta coluna irá receber o tipo de nuvem registrada.';


-- Nova tabela para Pressão Atmosférica
CREATE TABLE TBL_Pressao (
    Id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Data          DATE NOT NULL,
    Hora          NUMBER(2) NOT NULL,
    Pressao_atm   FLOAT(3)
);

COMMENT ON COLUMN TBL_Pressao.Id IS
    'Esta coluna irá receber o Id da pressão atmosférica registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Pressao.Data IS
    'Esta coluna irá receber a data da pressão atmosférica registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Pressao.Hora IS
    'Esta coluna irá receber a hora da pressão atmosférica registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Pressao.Pressao_atm IS
    'Esta coluna irá receber o valor da pressão atmosférica registrada.';


-- Atualização da tabela TBL_Previsao com as chaves estrangeiras e sem as colunas de temperatura e umidade
CREATE TABLE TBL_Previsao (
    Id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Zona_Id       NUMBER NOT NULL,
    Data            DATE NOT NULL,
    Hora            NUMBER(2) NOT NULL,
    Temperatura_Id  NUMBER,
    Umidade_Id      NUMBER,
    Ventania_Id     NUMBER,
    Precipitacao_Id NUMBER,
    Nuvem_Id        NUMBER,
    Pressao_Id      NUMBER,
    FOREIGN KEY (Temperatura_Id) REFERENCES TBL_Temperatura(Id),
    FOREIGN KEY (Umidade_Id) REFERENCES TBL_Umidade(Id),
    FOREIGN KEY (Zona_Id) REFERENCES TBL_Zona(Id),
    FOREIGN KEY (Ventania_Id) REFERENCES TBL_Ventania(Id),
    FOREIGN KEY (Precipitacao_Id) REFERENCES TBL_Precipitacao(Id),
    FOREIGN KEY (Nuvem_Id) REFERENCES TBL_Nuvem(Id),
    FOREIGN KEY (Pressao_Id) REFERENCES TBL_Pressao(Id)
);

COMMENT ON COLUMN TBL_Previsao.Id IS
    'Esta coluna irá receber o Id da previsão registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao.Zona_Id IS
    'Esta coluna irá receber o Id da zona registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao.Data IS
    'Esta coluna irá receber a data da previsão registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao.Hora IS
    'Esta coluna irá receber a hora da previsão registrada e seu conteúdo é obrigatório.';
	
COMMENT ON COLUMN TBL_Previsao.Temperatura_Id IS
    'Esta coluna irá receber a chave estrangeira para a temperatura registrada.';
	
COMMENT ON COLUMN TBL_Previsao.Umidade_Id IS
    'Esta coluna irá receber a chave estrangeira para a umidade registrada.';

COMMENT ON COLUMN TBL_Previsao.Ventania_Id IS
    'Esta coluna irá receber a chave estrangeira para a ventania registrada.';

COMMENT ON COLUMN TBL_Previsao.Precipitacao_Id IS
    'Esta coluna irá receber a chave estrangeira para a precipitação registrada.';

COMMENT ON COLUMN TBL_Previsao.Nuvem_Id IS
    'Esta coluna irá receber a chave estrangeira para a nuvem registrada.';

COMMENT ON COLUMN TBL_Previsao.Pressao_Id IS
    'Esta coluna irá receber a chave estrangeira para a pressão atmosférica registrada.';


CREATE TABLE TBL_Previsao_Futura (
    Id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Zona_Id       NUMBER NOT NULL,
    Data_Referencia DATE NOT NULL,
    Data_Futura     DATE NOT NULL,
    Hora            NUMBER(2) NOT NULL,
    Temperatura_Max FLOAT(3),
    Temperatura_Min FLOAT(3),
    Umidade_Max     FLOAT(3),
    Umidade_Min     FLOAT(3),
    Ventania        FLOAT(3),
    Precipitacao    FLOAT(3),
    Nuvem           VARCHAR2(50),
    Pressao         FLOAT(3),
    FOREIGN KEY (Zona_Id) REFERENCES TBL_Zona(Id)
);

COMMENT ON COLUMN TBL_Previsao_Futura.Id IS
    'Esta coluna irá receber o Id da previsão futura registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao_Futura.Zona_Id IS
    'Esta coluna irá receber o Id da zona registrada e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao_Futura.Data_Referencia IS
    'Esta coluna irá receber a data de referência da previsão futura e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao_Futura.Data_Futura IS
    'Esta coluna irá receber a data futura prevista e seu conteúdo é obrigatório.';

COMMENT ON COLUMN TBL_Previsao_Futura.Hora IS
    'Esta coluna irá receber a hora prevista e seu conteúdo é obrigatório.';
	
COMMENT ON COLUMN TBL_Previsao_Futura.Temperatura_Max IS
    'Esta coluna irá receber a chave estrangeira para a temperatura máxima futura.';
    
COMMENT ON COLUMN TBL_Previsao_Futura.Temperatura_Min IS
    'Esta coluna irá receber a chave estrangeira para a temperatura minima futura.';
	
COMMENT ON COLUMN TBL_Previsao_Futura.Umidade_Max IS
    'Esta coluna irá receber a chave estrangeira para a umidade futura.';
    
COMMENT ON COLUMN TBL_Previsao_Futura.Umidade_Min IS
    'Esta coluna irá receber a chave estrangeira para a umidade futura.';

COMMENT ON COLUMN TBL_Previsao_Futura.Ventania IS
    'Esta coluna irá receber a chave estrangeira para a ventania futura.';

COMMENT ON COLUMN TBL_Previsao_Futura.Precipitacao IS
    'Esta coluna irá receber a chave estrangeira para a precipitação futura.';

COMMENT ON COLUMN TBL_Previsao_Futura.Nuvem IS
    'Esta coluna irá receber a chave estrangeira para a nuvem futura.';

COMMENT ON COLUMN TBL_Previsao_Futura.Pressao IS
    'Esta coluna irá receber a chave estrangeira para a pressão atmosférica futura.';